### PR TITLE
[pkg] Update querystringify and other deps (closes #175)

### LINKED ISSUE #175: Update querystringify to 2.1.1 to fix core bug with uncaught exception
v2.1.1 of querystringify was released which fixes an issue where it does not match Node's graceful fallback for decoding URI

https://github.com/unshiftio/querystringify/commit/30e1d1956d474a81a0d0fec9ad4f00a928b1a2d5

per Node's built-in:

> By default, the querystring.unescape() method will attempt to use the JavaScript built-in decodeURIComponent() method to decode. If that fails, a safer equivalent that does not throw on malformed URLs will be used.

https://nodejs.org/api/querystring.html#querystring_querystring_unescape_str

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by lpinca** [comment]
Is this really needed? All deps use caret ranges and the latest version in that range is used on install.
Dependencies and dev dependencies are regularly updated by Greenkeeper.

**Comment by niftylettuce** [comment]
Per my comment in #175, I think this is 100% necessary.  The main thing in doing this is that we'll publish a new version of `url-parse`, and can then do `npm deprecate url-parse@"<X.X.X" "Please upgrade to vX.X.X+ as an uncaught exception bug in querystringify has been fixed"

**Comment by lpinca** [comment]
Ok it makes sense for the `querystringify` dep.

**Comment by lpinca** [comment]
Thank you.

cc: @3rd-Eden as I can't publish on npm.

**Comment by niftylettuce** [comment]
Thank you all so much for being so prompt and continuing to dedicate time to open source. 👏

**Comment by 3rd-Eden** [comment]
Published as 1.4.7

**Pull request merged**
