### PR TITLE
Special case the `file:` protocol

### LINKED ISSUE #203: Incorrect protocol/hostname parsing
According to [URL](https://en.wikipedia.org/wiki/URL) and [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax) definitions, after the `scheme` (or `protocol`) followed by colon (`:`), there is an optional `authority` (or `hostname`) component preceded by **two** slashes (`//`).

The [File URI](https://en.wikipedia.org/wiki/File_URI_scheme#How_many_slashes?) describes exactly how many slashes can be a part of the `authority` as:

> A valid file URI must therefore begin with either `file:/path` (no hostname), `file:///path` (empty hostname), or `file://hostname/path`.

When parsing an iOS file URL which looks like this:
```
file:///Users/username/Library/Developer/CoreSimulator/Devices/00000000-0000-0000-0000-000000000000/data/Containers/Data/Application/00000000-0000-0000-0000-000000000000/Documents/Inbox/dummy.pdf
```
the parser incorrectly takes all 3 slashes as a `host` predecessor (due to protocol regex looking for `([\\/]{1,})?`, so 1 or more slashes), and takes the `Users` as a `host`, and the rest (starting with `/username`) as the path.
To properly parse this file URL, only 2 slashes should be used as a `host` predecessor, while 3rd slash should be the beginning of a path (thus resulting with an empty `host`).

Exact issue that this is causing is that the `host` is lowercased, and `toString` function always uses 2 slashes when building the string, so parsing above file URL, and using `toString` on it results with:
```
file://users/username/Library/Developer/CoreSimulator/Devices/00000000-0000-0000-0000-000000000000/data/Containers/Data/Application/00000000-0000-0000-0000-000000000000/Documents/Inbox/dummy.pdf
```
which is an incorrect file URL on iOS, and cannot be accessed.

Changing the `protocolre` from `/^([a-z][a-z0-9.+-]*:)?([\\/]{1,})?([\S\s]*)/i` to `/^([a-z][a-z0-9.+-]*:)?([\\/]{2})?([\S\s]*)/i` (so that `([\\/]{2})?` will take 0 or 2 slashes) fixes this issue.

### PR DESCRIPTION
**Pull request by lpinca**
Fixes #203

### CODE REVIEW

**Comment by lpinca** [comment]
@3rd-Eden @Swaagie can you please cut a new release? I can't publish to npm.

**Comment by krassowski** [comment]
Looking forward to a new release :)

**Comment by pcafstockf** [comment]
ldap:///
I believe the same special case is needed for ldap (see https://ldap.com/ldap-urls/).

I can open a new issue if you like?
Just added a comment here, in case you wanted to bundle it into this PR ?

**Comment by lpinca** [comment]
@pcafstockf see https://github.com/unshiftio/url-parse/issues/205.

**Pull request merged**
