### PR TITLE
Add typings.

### LINKED ISSUE #46: Please add this typings to your git so that it can stay in sync with the code
Thanks for the great work.

Here is the typings:
https://gist.github.com/nertzy/d3110cae677913c476e8b4895eeaf412

### PR DESCRIPTION
**Pull request by darrinholst**
Resolves #46.

Adding this to `package.json` will allow typescript to find it without the need to add it to `@types`.

### CODE REVIEW

**Comment by GeraldIstar** [comment]
`origin` is missing?

**Comment by ChernenkoPaul** [comment]
FYI: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20233

**Comment by 3rd-Eden** [comment]
Thanks <3

**Comment by 3rd-Eden** [comment]
@DimitryDushkin In that case, it would make sense to update the typings in the definitelyTyped repository.

**Comment by DimitryDushkin** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26947

**Pull request closed without merging**
