### PR TITLE
Sanitize only special URLs

### PR DESCRIPTION
**Pull request by lpinca**
Fixes https://github.com/unshiftio/url-parse/pull/208#discussion_r675788224.

### CODE REVIEW

**Comment by enahum** [comment]
this is causing issues. let's say I have a path `file:://file-path/file.png` after parsing the `href` prop is returning `file:///file-path/file.png` notice the third slash after the protocol.

**Comment by lpinca** [comment]
@enahum I see that the Node.js URL parser handles this differently

```
new URL('file://file-path/file')
URL {
  href: 'file://file-path/file',
  origin: 'null',
  protocol: 'file:',
  username: '',
  password: '',
  host: 'file-path',
  hostname: 'file-path',
  port: '',
  pathname: '/file',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

 but the issue it not caused by this commit. This behavior was introduced with d2979b586d8c7751e0c77f127d9ce1b2143cc0c9. I'll see if I can fix it.

**Comment by lpinca** [comment]
Anyway this is kind of funny:

```
 new URL('file:file-path/file')
URL {
  href: 'file:///file-path/file',
  origin: 'null',
  protocol: 'file:',
  username: '',
  password: '',
  host: '',
  hostname: '',
  port: '',
  pathname: '/file-path/file',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

```
URL {
  href: 'file:///file-path/file',
  origin: 'null',
  protocol: 'file:',
  username: '',
  password: '',
  host: '',
  hostname: '',
  port: '',
  pathname: '/file-path/file',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

```
URL {
  href: 'file://file-path/file',
  origin: 'null',
  protocol: 'file:',
  username: '',
  password: '',
  host: 'file-path',
  hostname: 'file-path',
  port: '',
  pathname: '/file',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

```
URL {
  href: 'file:///file-path/file',
  origin: 'null',
  protocol: 'file:',
  username: '',
  password: '',
  host: '',
  hostname: '',
  port: '',
  pathname: '/file-path/file',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

I wonder if a `file:` url can have a `host`.

**Comment by lpinca** [comment]
@enahum https://github.com/unshiftio/url-parse/pull/210 should fix the issue.

**Comment by 3rd-Eden** [comment]
Published as 1.5.3

**Pull request merged**
